niteshbalusu11/lndboss

main/background.ts, main/commands/chartChainFees/chart_chain_fees_command.ts, main/commands/index.ts, main/preload.ts, package.json, playwright.config.ts, renderer/commands.ts, renderer/output/ChartChainFeesOutput.tsx, renderer/output/index.ts, renderer/pages/Balance.tsx, renderer/pages/ChartChainFees.tsx, renderer/register_charts.ts, renderer/renderer.d.ts, renderer/standard_components/SubmitButton.tsx, renderer/types.ts, tests/client/chartChainFees.test.ts, tests/server/chartChainFees.test.ts, yarn.lock
https://github.com/niteshbalusu11/lndboss/issues/12
=> added chart-chain-fees command

.gitignore, electron-builder.yml, main/background.ts, main/commands/chartPaymentsReceived/chart_payments_received_command.ts, main/commands/index.ts, main/preload.ts, renderer/commands.ts, renderer/output/ChartPaymentsReceivedOutput.tsx, renderer/output/index.ts, renderer/pages/ChartPaymentsReceived.tsx, renderer/pages/result/ChartPaymentsReceivedResult.tsx, renderer/renderer.d.ts, renderer/types.ts, tests/client/chartPaymentsReceived.test.ts, tests/server/chartPaymentsReceived.test.ts
added support for chart-payments-received command
=> [chart-payments-received]- Added command support

src/client/commands.ts, src/client/output/CertValidityDaysOutput.tsx, src/client/output/index.ts, src/client/pages/CertValidityDays.tsx, src/client/standard_components/ContainerStyle.tsx, src/client/standard_components/index.ts, src/server/app.module.ts, src/server/commands/certValidityDays/cert_validity_days_command.ts, src/server/commands/index.ts, src/server/modules/balance/balance.controller.ts, src/server/modules/cert-validity-days/cert-validity-days.controller.ts, src/server/modules/cert-validity-days/cert-validity-days.module.ts, src/server/modules/cert-validity-days/cert-validity-days.service.ts, src/server/utils/constants.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/certValidityDays.test.ts, tests/server/balance.test.ts, tests/server/certValidityDays.test.ts, tests/server/chainDeposit.test.ts, tests/server/chartChainFees.test.ts, tests/server/chartFeesEarned.test.ts, tests/server/chartFeesPaid.test.ts, tests/server/chartPaymentsReceived.test.ts, tests/server/tags.test.ts, tests/utils/spawn_lightning.ts, tests/utils/spawn_lightning_server.ts
Add the cert-validity-days command and the associated test cases
=> add cert-validity-days command and test cases

src/client/hooks/useLoading.ts, src/client/hooks/useNotify.ts, src/client/pages/Authenticate.tsx, src/client/pages/result/AccountingResult.tsx, src/client/pages/result/ChartChainFeesResult.tsx, src/client/pages/result/ChartFeesEarnedResult.tsx, src/client/pages/result/ChartFeesPaidResult.tsx, src/client/pages/result/ChartPaymentsReceivedResult.tsx, src/client/utils/axios.ts, src/server/lnd/authenticated_lnd.ts, src/server/lnd/get_saved_credentials.ts, src/server/lnd/get_saved_nodes.ts, src/server/lnd/lnd_credentials.ts, src/server/lnd/put_saved_credentials.ts, src/shared/commands.dto.ts, tests/client/01login.test.ts, tests/client/accounting.test.ts, tests/server/01login.test.ts, tests/utils/global_spawn_lightning.ts
Added loading dialog when waiting for response from server.
Added support for setting paths to credentials.
Updated test cases
=> Add loading dialog, update test cases, support for paths to credentials

src/client/commands.ts, src/client/hooks/useNotify.ts, src/client/output/FindOutput.tsx, src/client/pages/Find.tsx, src/server/app.module.ts, src/server/commands/find/find_command.ts, src/server/commands/index.ts, src/server/modules/find/find.controller.ts, src/server/modules/find/find.module.ts, src/server/modules/find/find.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/find.test.ts, tests/server/find.test.ts
Added support for bos find command
=> Added support for bos find command

src/server/lnd/get_saved_credentials.ts, src/server/lnd/put_saved_credentials.ts, src/server/utils/constants.ts, src/server/utils/global_functions.ts
Added support for encrypting macaroon is saved credentials is used.
=> Encrypt macaroon

src/client/commands.ts, src/client/output/ForwardsOutput.tsx, src/client/pages/Forwards.tsx, src/server/app.module.ts, src/server/commands/forwards/forwards_command.ts, src/server/commands/index.ts, src/server/modules/forwards/forwards.controller.ts, src/server/modules/forwards/forwards.module.ts, src/server/modules/forwards/forwards.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/forwards.test.ts, tests/server/forwards.test.ts
Fixes #41
Added support for bos forwards command
=> [forwards]: Add support for bos forwards command

README.md, src/client/commands.ts, src/client/output/ChainfeesOutput.tsx, src/client/output/index.ts, src/client/pages/Chainfees.tsx, src/client/pages/Closed.tsx, src/client/pages/Find.tsx, src/client/pages/Forwards.tsx, src/server/app.module.ts, src/server/commands/chainfees/chainfees_command.ts, src/server/commands/index.ts, src/server/modules/chainfees/chainfees.controller.ts, src/server/modules/chainfees/chainfees.module.ts, src/server/modules/chainfees/chainfees.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/balance.test.ts, tests/client/chainfees.test.ts, tests/server/chainfees.test.ts
=> [chain-fees]: Add support for bos chain-fees command

README.md, playwright.config.ts, src/client/commands.ts, src/client/output/PriceOutput.tsx, src/client/pages/Accounting.tsx, src/client/pages/Balance.tsx, src/client/pages/Chainfees.tsx, src/client/pages/ChartFeesEarned.tsx, src/client/pages/ChartFeesPaid.tsx, src/client/pages/Price.tsx, src/client/pages/Tags.tsx, src/server/app.module.ts, src/server/commands/index.ts, src/server/commands/price/price_command.ts, src/server/modules/price/price.controller.ts, src/server/modules/price/price.module.ts, src/server/modules/price/price.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/price.test.ts, tests/server/price.test.ts
=> [price]: Add support for bos price command

package.json, src/client/commands.ts, src/client/pages/Rebalance.tsx, src/client/pages/result/RebalanceResult.tsx, src/client/standard_components/StartFlexBoxBlack.tsx, src/client/utils/axios.ts, src/server/app.module.ts, src/server/commands/index.ts, src/server/commands/rebalance/rebalance_command.ts, src/server/modules/rebalance/rebalance.controller.ts, src/server/modules/rebalance/rebalance.module.ts, src/server/modules/rebalance/rebalance.service.ts, src/server/modules/socket/socket.gateway.ts, src/server/modules/socket/socket.module.ts, src/server/utils/global_functions.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/accounting.test.ts, tests/client/chartChainFees.test.ts, tests/client/chartFeesEarned.test.ts, tests/client/chartFeesPaid.test.ts, tests/client/chartPaymentsReceived.test.ts, tests/client/rebalance.test.ts, tests/client/tags.test.ts, tests/server/rebalance.test.ts, tests/utils/setAccessToken.ts, yarn.lock
Added support for websockets and rebalance command.
https://github.com/niteshbalusu11/lndboss/issues/47
=> Support for Web-sockets and rebalance command

package.json, src/server/app.module.ts, src/server/main.ts, src/server/modules/boslogger/boslogger.module.ts, src/server/modules/boslogger/boslogger.service.ts, src/server/modules/cron/cron.module.ts, src/server/modules/cron/cron.service.ts, yarn.lock
=> Improve logging.

.github/PULL_REQUEST_TEMPLATE.md, package.json, src/client/pages/schedulers/RebalanceScheduler.tsx, tests/client/rebalance.test.ts, yarn.lock
Fixes #65
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> bump bos dependency

README.md, src/server/commands/chartChainFees/chart_chain_fees_command.ts, src/server/commands/chartFeesEarned/chart_fees_earned_command.ts, src/server/commands/chartFeesPaid/chart_fees_paid_command.ts, src/server/commands/chartPaymentsReceived/chart_payments_received_command.ts, src/server/commands/price/price_command.ts, src/server/modules/chart-chain-fees/chart-chain-fees.service.ts, src/shared/commands.dto.ts, tests/client/send.test.ts
Fixes #73
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> Make node optional in API calls.

README.md, playwright.config.ts, src/client/commands.ts, src/client/output/ReconnectOutput.tsx, src/client/pages/commands/Reconnect.tsx, src/server/app.module.ts, src/server/commands/index.ts, src/server/commands/reconnect/reconnect_command.ts, src/server/modules/reconnect/reconnect.controller.ts, src/server/modules/reconnect/reconnect.module.ts, src/server/modules/reconnect/reconnect.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/reconnect.test.ts, tests/server/reconnect.test.ts
Fixes #77
Added support bos reconnect command and corresponding test cases.
Fixes #77
=> [reconnect]: Add support for bos reconnect command

Dockerfile, package.json
Fixes bug where docker builds are failing after adding support for npm publish.
Fixes # (issue)
=> Fix docker build issues

.vscode/settings.json, README.md, playwright.config.ts, src/client/commands.ts, src/client/output/GraphOutput.tsx, src/client/pages/commands/Graph.tsx, src/server/commands/graph/graph_command.ts, tests/client/graph.test.ts, tests/server/graph.test.ts
Fixes #81
Add client side of graph command.
Fixes #81
=> [graph]: Add support for bos graph command

README.md, package.json, yarn.lock
Remove unused dotenv dependency
=> remove dotenv dependency

README.md, src/client/commands.ts, src/client/pages/commands/Pay.tsx, src/client/pages/result/PayResult.tsx, src/server/commands/index.ts, src/server/commands/pay/pay_command.ts, src/server/commands/send/send_command.ts, src/server/modules/commands/commands.controller.ts, src/server/modules/commands/commands.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/pay.test.ts, tests/server/pay.test.ts
Fixes #93
Adds support for bos pay command
=> [pay]: Add support for bos pay command

README.md, package.json, src/client/commands.ts, src/client/output/ChartChainFeesOutput.tsx, src/client/pages/commands/ChartChainFees.tsx, src/client/pages/commands/ChartFeesEarned.tsx, src/client/pages/commands/ChartFeesPaid.tsx, src/client/pages/commands/ChartPaymentsReceived.tsx, src/client/pages/result/ChartChainFeesResult.tsx, src/client/pages/result/ChartFeesEarnedResult.tsx, src/client/pages/result/ChartFeesPaidResult.tsx, src/client/pages/result/ChartPaymentsReceivedResult.tsx, src/client/standard_components/app-components/BasicDatePicker.tsx, src/client/standard_components/app-components/index.ts, src/server/commands/chartChainFees/chart_chain_fees_command.ts, src/server/commands/chartFeesEarned/chart_fees_earned_command.ts, src/server/commands/chartFeesPaid/chart_fees_paid_command.ts, src/server/commands/chartPaymentsReceived/chart_payments_received_command.ts, src/server/external_services_utils/amboss_health_check.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/server/chartChainFees.test.ts, tests/server/chartFeesEarned.test.ts, tests/server/chartFeesPaid.test.ts, tests/server/chartPaymentsReceived.test.ts, yarn.lock
Fixes #92
Adds date/time picker for all chart commands
Fixes #92
=> Add date ranges to chart commands

src/client/commands.ts, src/client/output/CallOutput.tsx, src/client/output/index.ts, src/client/pages/commands/Call.tsx, src/client/standard_components/lndboss/RawApiList.tsx, src/client/standard_components/lndboss/index.ts, src/client/utils/axios.ts, src/client/utils/validate_call_command_args.ts, src/server/commands/call/call_command.ts, src/server/commands/index.ts, src/server/modules/commands/commands.controller.ts, src/server/modules/commands/commands.service.ts, src/shared/raw_api.ts, tests/client/call.test.ts, tests/server/call.test.ts
Added support for bos call command and marked it as experimental for now.
Fixes #97
=> Added support for call command (experimental)

src/client/dashboard/listItems.tsx, src/client/pages/commands/Rebalance.tsx, src/client/pages/preferences/UserPreferences.tsx, src/client/pages/schedulers/RebalanceScheduler.tsx, src/client/utils/constants.ts, src/server/commands/rebalance/auto_rebalance_command.ts, src/server/external_services_utils/amboss_health_check.ts, src/server/modules/commands/commands.controller.ts, src/server/modules/commands/commands.service.ts, src/server/modules/external-services/external-services.service.ts, src/server/settings/check_amboss_health_setting.ts, src/server/settings/check_scheduled_rebalance_setting.ts, src/server/settings/get_settings.file.ts, src/server/settings/index.ts, src/server/settings/settings.json, src/server/settings/write_settings_file.ts, tests/client/rebalance.test.ts, tsconfig.json
Fixes #101
Added the ability to control automated rebalances and amboss health check from user preferences page to turn them on or off.
This could be a potential breaking change since existing automated rebalance won't run unless its turned on from settings.
=> Add switches in the UI for auto rebalance and emboss health check

README.md, src/client/commands.ts, src/client/pages/commands/ChartPaymentsReceived.tsx, src/client/pages/result/ChartPaymentsReceivedResult.tsx, src/server/commands/chartPaymentsReceived/chart_payments_received_command.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/chartPaymentsReceived.test.ts, tests/server/chartPaymentsReceived.test.ts
Fixes #108
Added for and query flags for chart-payments-received command.
=> [chart-payments-received]: Add count and for flags

playwright.config.ts, src/client/next.config.js, tests/client/call.test.ts
Add swcMinify to next config to speed up build times.
=> Speed up build times with swcminify

README.md, src/client/commands.ts, src/client/next.config.js, src/client/output/FeesOutput.tsx, src/client/output/index.ts, src/client/pages/commands/Fees.tsx, src/server/app.module.ts, src/server/commands/fees/fees_command.ts, src/server/commands/index.ts, src/server/modules/fees/fees.controller.ts, src/server/modules/fees/fees.module.ts, src/server/modules/fees/fees.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/fees.test.ts, tests/server/fees.test.ts, tests/utils/spawn_lightning_cluster.ts
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #115
=> Add support for bos fees command

src/client/utils/cookie.ts
Fix a bug where cookies don't work if using an IP address with http
=> Cookie-bug-fixes

SERVER.md, src/client/commands.ts, src/client/dashboard/PendingChart.tsx, src/client/pages/commands/Rebalance.tsx, src/client/pages/result/RebalanceResult.tsx, src/server/commands/rebalance/auto_rebalance_command.ts, src/server/commands/rebalance/rebalance_command.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/server/rebalance.test.ts
Addeed --avoid-high-fee-routes flag to rebalance command that avoids routes greater than max-fee-rate.
=> Add avoid-high-fee-routes to rebalance

README.md, SERVER.md, package.json, src/client/commands.ts, src/client/output/UtxosOutput.tsx, src/client/pages/commands/Utxos.tsx, src/server/commands/index.ts, src/server/commands/utxos/utxos_command.ts, src/server/modules/commands/commands.controller.ts, src/server/modules/commands/commands.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/utxos.test.ts, tests/server/utxos.test.ts
Fixes #135
Added bos utxos command
=> [utxos]: Add utxos command

package.json, src/client/dashboard/listItems.tsx, src/client/pages/preferences/QuickTools.tsx, src/client/standard_components/app-components/StandardHomeButtonLink.tsx, src/client/standard_components/app-components/quicktools/CreateChainAddress.tsx, src/client/standard_components/app-components/quicktools/CreateInvoice.tsx, src/client/standard_components/app-components/quicktools/PayInvoice.tsx, src/client/standard_components/app-components/quicktools/SendOnchain.tsx, src/client/standard_components/app-components/quicktools/index.ts, src/client/utils/constants.ts, src/server/commands/balance/balance_command.ts, src/server/commands/index.ts, src/server/commands/invoice/invoice_command.ts, src/server/modules/commands/commands.controller.ts, src/server/modules/commands/commands.service.ts, src/shared/commands.dto.ts, src/shared/types.ts, tests/client/quicktools.test.ts, tests/server/balance.test.ts, tests/utils/constants.ts, yarn.lock
Add a quick tools page to create invoice, create chain address, pay invoice and send funds onchain.
Fixes a bug where balance command detailed is broken.
=> Add-quick-tools-page

README.md, SERVER.md, src/client/commands.ts, src/client/output/InvoiceOutput.tsx, src/client/output/index.ts, src/client/pages/commands/ChainDeposit.tsx, src/client/pages/commands/Graph.tsx, src/client/pages/commands/Invoice.tsx, src/client/standard_components/app-components/quicktools/CreateInvoice.tsx, src/client/standard_components/app-components/quicktools/PayInvoice.tsx, tests/client/invoice.test.ts, tests/client/price.test.ts, tests/server/price.test.ts
Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>
Added invoice command
=> Add invoice command

src/client/commands.ts, src/client/output/DecryptOutput.tsx, src/client/output/EncryptOutput.tsx, src/client/output/index.ts, src/client/pages/commands/Decrypt.tsx, src/client/pages/commands/Encrypt.tsx, src/server/commands/decrypt/decrypt_command.ts, src/server/commands/encrypt/encrypt_command.ts, src/server/commands/index.ts, src/server/modules/commands/commands.controller.ts, src/server/modules/commands/commands.service.ts, src/shared/commands.dto.ts, src/shared/types.ts
Added encrypt and decrypt commands
=> added encrypt and decrypt commands
